version: '3'
services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  bookingmanagement:
    image: gompermike/bookingmanagement:latest
    depends_on:
     - rabbitmq
     - waitforrabbit
    ports: 
     - "9090"

  waitforrabbit:
    image: dadarek/wait-for-dependencies
    depends_on:
      - rabbitmq
    command: rabbitmq:5672

volumes:
  rabbitmqdata:
    external: true