version: '3'
services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  # invoicingmanagement:
  #   image: tolgaelbir/invoicingmanagement:latest
  #   depends_on:
  #    - rabbitmq
  #    - waitforrabbit
  #   build:
  #     context: .
  #     dockerfile: /invoicing/Dockerfile
  #   ports: 
  #    - "8080"

  bookingmanagement:
    image: tolgaelbir/bookingmanagement:latest
    depends_on:
      - rabbitmq
      - waitforrabbit
    build:
      context: .
      dockerfile: Booking/Dockerfile
    ports:
      - "9090"

  # atcmanagement:
  #   image: gompermike/atcmanagement:latest
  #   depends_on:
  #     - rabbitmq
  #     - waitforrabbit
  #   ports:
  #     - "1010"    

  # bordersecuritymanagement:
  #   image: gompermike/bordersecuritymanagement:latest
  #   depends_on:
  #     - rabbitmq
  #     - waitforrabbit
  #   ports:
  #     - "2020"

  checkinmanagement:
    image: tolgaelbir/checkinmanagement:latest
    depends_on:
      - rabbitmq
      - waitforrabbit
    ports:
      - "3030"

  # securitymanagement:
  #   image: gompermike/securitymanagement:latest
  #   depends_on:
  #     - rabbitmq
  #     - waitforrabbit
  #   ports:
  #     - "4040"

  waitforrabbit:
    image: dadarek/wait-for-dependencies
    depends_on:
      - rabbitmq
    command: rabbitmq:5672

volumes:
  rabbitmqdata:
    external: true