version: '3'
services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  sqldatabase:
    image: microsoft/mssql-server-linux
    restart: always
    volumes: 
      - datafiles:/var/lib/sqldb
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Atleast8characters!

  waitforrabbit:
    image: dadarek/wait-for-dependencies
    depends_on:
      - rabbitmq
    command: rabbitmq:5672

  flightmanagement:
    image: avansairportapp/flightmanagement_1
    depends_on:
      - rabbitmq
      - waitforrabbit
      - sqldatabase
    build:
      context: .
      dockerfile: FlightManagement/Dockerfile
    ports:
      - "5001"
    restart: always
    environment: 
      - DBHOST=sqldatabase
      - DBPORT=1433
      - DBUSER=sa
      - DBPASSWORD=Atleast8characters!

volumes:
  rabbitmqdata:
    external: true
  datafiles:
    external: true